FROM zalando/ubuntu:14.04.1-1
MAINTAINER Henning Jacobs <henning.jacobs@zalando.de>

RUN apt-get update
RUN curl -o /tmp/openjdk.deb http://de.archive.ubuntu.com/ubuntu/pool/universe/o/openjdk-8/openjdk-8-jre-headless_8u40~b09-1_amd64.deb
# http://stackoverflow.com/questions/8477036/how-to-make-debian-package-install-dependencies
RUN dpkg -i /tmp/openjdk.deb || apt-get -f --force-yes --yes install
RUN dpkg -i /tmp/openjdk.deb
RUN rm /tmp/openjdk.deb

# tarball as generated by "sbt universal:package-zip-tarball"
ADD target/universal/docker-registry-play-0.1-SNAPSHOT.tgz /app

CMD ["/app/docker-registry-play-0.1-SNAPSHOT/bin/docker-registry-play"]
