FROM zalando/openjdk:8u40-b09-2
MAINTAINER Henning Jacobs <henning.jacobs@zalando.de>

# tarball as generated by "sbt universal:package-zip-tarball"
ADD target/universal/docker-registry-play-0.1-SNAPSHOT.tgz /app

CMD ["/app/docker-registry-play-0.1-SNAPSHOT/bin/docker-registry-play"]
